/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.componentes.componente2A;

import java.io.Serializable;
import javax.swing.DefaultListModel;

/**
 *
 * @author diurno
 */
public class Componente2A extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form Componente2A
     */
    private Object[][] matrizDatos;
    private boolean tieneMensaje;
    private String mensaje;
    private final DefaultListModel<String> listModel;
    
    public Componente2A() {
        initComponents();
        
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        matrizDatos = new Object[500][500];
        mensaje = "Prueba";
        
        cargarDatos(matrizDatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param matrizDatos
     */
    //setters
    public void setMatrizDatos(Object[][] matrizDatos){
        this.matrizDatos = matrizDatos;
        cargarDatos(matrizDatos);
    }
    public void setTieneMensaje(boolean tieneMensaje){
        this.tieneMensaje = tieneMensaje;
        cargarDatos(matrizDatos);
    }
    public void setMensaje(String mensaje){
        this.mensaje = mensaje;
        if (tieneMensaje) {
            cargarDatos(matrizDatos);
        }
    }
    //getters
    public Object[][] getMatrizDatos(){
        return (matrizDatos);
    }
    public boolean getTieneMensaje(){
        return (tieneMensaje);
    }
    public String getMensaje(){
        return (mensaje);
    }
    public int getIndiceSeleccionado(){
        return (jList1.getSelectedIndex());
    }
    //metodos
    public void setJLabelText(String text){
        jLabel1.setText(text);
    }
    
    public String getCodigoSeleccionado() {
        int indice = jList1.getSelectedIndex();

        if (indice == -1) {
            return null; // No hay selección válida
        }

        if (tieneMensaje && indice == 0) {
            return null; // Si el primer elemento es un mensaje, no es un dato válido
        }

        // Ajustar el índice si hay mensaje
        if (tieneMensaje) {
            indice = indice - 1;
        }

        return matrizDatos[indice][0].toString();
    }
    
    public final void cargarDatos(Object[][] datos){
        listModel.clear(); // Limpiar lista antes de actualizar
    
        if (tieneMensaje) {
            // Si tiene mensaje, añadirlo primero
            listModel.addElement(mensaje);
        }

        // Cargar el resto de los datos
        for (Object[] fila : datos) {
            if (fila.length > 1) { // Verifica que hay al menos 2 columnas
                listModel.addElement(fila[1].toString()); // Agregar la segunda columna
            }
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("Nombre campo");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
