/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyecto.componentes.componente3;


/**
 *
 * @author Meu
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.EventListenerList;

public class Componente3 extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form Componente3
     */
    private Object[][] matrizDatos;
    private final DefaultComboBoxModel<String> comboBoxModel;
    private String textoBusqueda;
    
    private final EventListenerList listenerList = new EventListenerList();
    
    public Componente3() {
        initComponents();
        comboBoxModel = new DefaultComboBoxModel<>();
        jComboBox1.setModel(comboBoxModel);
        
        jTextField1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                notificarBusqueda();
            }
        });
         jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                notificarBusqueda();
            }
        });
    }
    
    private void notificarBusqueda() {
        textoBusqueda = jTextField1.getText();
        fireBusquedaRealizada();
    }
    
    public void setMatrizDatos(Object[][] datos) {
        this.matrizDatos = datos;
        cargarDatos();
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jTextField1 = jTextField1;
    }
    
    public Object[][] getMatrizDatos() {
        return matrizDatos;
    }
    
    public void setJLabelText(String text) {
        jLabel1.setText(text);
    }
    
    public String getTextoBusqueda() {
        return textoBusqueda;
    }
    
    public String getCodigoSeleccionado() {
        int index = jComboBox1.getSelectedIndex();
        if (index == -1) {
            return null;
        }
        return matrizDatos[index][0].toString();
    }
    
    private void cargarDatos() {
        comboBoxModel.removeAllElements();
        if (matrizDatos != null) {
            for (Object[] fila : matrizDatos) {
                comboBoxModel.addElement(fila[1].toString());
            }
        }
    }
    
    private void fireBusquedaRealizada() {
        Componente3Object event = new Componente3Object(this, textoBusqueda);
        for (Componente3Listener listener : listenerList.getListeners(Componente3Listener.class)) {
            listener.onBusquedaRealizada(event); // Notifica a los listeners registrados
        }
    }
    
    public void addComponente3Listener(Componente3Listener listener) {
        listenerList.add(Componente3Listener.class, listener);
    }
    
     public void removeComponente3Listener(Componente3Listener listener) {
        listenerList.remove(Componente3Listener.class, listener);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("nombre campo");
        add(jLabel1, new java.awt.GridBagConstraints());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jTextField1, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(jComboBox1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
